version: '3.6'
services:
  trashClient:
    image: node:latest
    container_name: trashClient
    working_dir: /app
    ports:
      - '3000:3000'
    depends_on:
      - trashServer
      - trashDB
    command: npm start
    volumes:
      - ./client:/app
  trashServer:
    image: node:latest
    container_name: trashServer
    ports:
      - '5000:5000'
    depends_on:
      - trashDB
    working_dir: /app
    volumes:
      - ./server:/app
    command: npm run start:dev
  
  trashDB:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=trashDB
    ports:
      - "5432:5432" 
    volumes: 
      - ./data/database-data:/var/lib/postgresql/data/
